# Generated by Django 4.0.4 on 2022-05-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('Movies', 'Movies'), ('NBA players', 'NBA players'), ('Animals', 'Animals'), ('Countries', 'Countries')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
